services:
  - type: web
    name: samruddhi-setu
    env: node
    plan: free
    buildCommand: npm install --prefix frontend --legacy-peer-deps && npm run build --prefix frontend && npm install --prefix server --legacy-peer-deps && npx prisma generate --schema server/prisma/schema.prisma && npm run build --prefix server
    startCommand: cd server && npx prisma db push && npm run db:seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: samruddhi-setu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: samruddhi-setu-db
    plan: free
    postgresMajorVersion: 16
